### ISSUE TITLE
ERR and exit when Idle.

### ISSUE THREAD

**Issue by nuentoter** [xynxynxyn/terminal-discord#12]
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at WebSocketConnection.onError (/home/koha/GIT/discord/terminal-discord/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/koha/GIT/discord/terminal-discord/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (/home/koha/GIT/discord/terminal-discord/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/koha/GIT/discord/terminal-discord/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/koha/GIT/discord/terminal-discord/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

******************************************************************************************************************************

Running on debian stretch, i3wm. 

node modules may lead somewhere....?

**Comment by xynxynxyn** [comment]
Error handling as added in [5e83fa0](https://github.com/xynxynxyn/terminal-discord/commit/5e83fa0c51eaaaa256a78e02a7a24c848b79db83) should prevent it from crashing. This is most likely not a client side issue so catching the error should solve the problem.
