### ISSUE TITLE
Crash after log-in: "TypeError: channel.fetchMessages is not a function"

### ISSUE THREAD

**Issue by smlavine** [xynxynxyn/terminal-discord#21]
Hello, this is an issue I have been experiencing with terminal-discord. What is odd is that the program worked, but I uninstalled it and then reinstalled, and it is now having this problem. I have a token stored in the config, file which it is reading. This is the complete output of the program:

```
Logging in...
Skaibae successfully logged in
> /usr/lib/node_modules/terminal-discord/index.js:442
    .fetchMessages({
     ^

TypeError: channel.fetchMessages is not a function
    at history (/usr/lib/node_modules/terminal-discord/index.js:442:6)
    at Client.client.on (/usr/lib/node_modules/terminal-discord/index.js:70:3)
    at emitNone (events.js:111:20)
    at Client.emit (events.js:208:7)
    at WebSocketConnection.triggerReady (/usr/lib/node_modules/terminal-discord/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/usr/lib/node_modules/terminal-discord/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at ReadyHandler.handle (/usr/lib/node_modules/terminal-discord/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:79:8)
    at WebSocketPacketManager.handle (/usr/lib/node_modules/terminal-discord/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/usr/lib/node_modules/terminal-discord/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/usr/lib/node_modules/terminal-discord/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
```

**Comment by xynxynxyn** [comment]
It seems like this issue is caused by the default channel being a voice channel.

I pushed an update to version 1.6.2. Please try that out and tell me if that fixed it.

**Comment by smlavine** [comment]
This fixed it. Thanks!
