### ISSUE TITLE
Can't enter any channels UnhandledPromiseRejectionWarnperty 'col' of undefined 

### ISSUE THREAD

**Issue by allycatty** [xynxynxyn/terminal-discord#25]
Same thing happens regardless of starting with sudo or user level.
```
getting channel list ready

>
[1] ↀᴥↀ
[2] ●ↀωↀ●✧
[3] 𝓣𝓱𝓮-𝓛𝓪𝔀
[4] 𝓖𝓸-𝓸𝓯𝓯-𝓼𝓲𝓼
[0] CANCEL

Choose one from list [1...4 / 0]: 1

>(node:8376) UnhandledPromiseRejectionWarnperty 'col' of undefined
    at update (/home/ally/.npm-packages/li/index.js:431:32)
    at channel.fetchMessages.then.m (/homedules/terminal-discord/index.js:469:7)
    at <anonymous>
    at process._tickCallback (internal/pro
(node:8376) UnhandledPromiseRejectionWarni. This error originated either by throwingthout a catch block, or by rejecting a pro .catch(). (rejection id: 4)

readline.js:1021
            throw err;
            ^

TypeError: Cannot read property 'col' of u
    at update (/home/ally/.npm-packages/li/index.js:431:32)
    at Interface.rl.on.line (/home/ally/.nrminal-discord/index.js:110:7)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:
    at Interface._line (readline.js:631:8)
    at Interface._ttyWrite (readline.js:91
    at ReadStream.onkeypress (readline.js:
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)

```

**Comment by xynxynxyn** [comment]
Sadly I can't reproduce this issue, but I pushed some checks and default values that should clear this.

However the cursor adjustment work this way.

**Comment by allycatty** [comment]
If you'd like I'd be happy to send you the virtualbox image I'm using.

**Comment by xynxynxyn** [comment]
Please do. It's most likely an issue with a 3rd party lib that I can do nothing about, but I'd still like to see it.
